WIP: convert ITS-90 guide samples
metanorma/mn-samples-bipm pull request #6
Opened 2020-10-22 22:09 UTC by manuel489

*As requested in https://github.com/metanorma/mn-samples-bipm/issues/2*

2020-10-23 18:30 UTC, ronaldtse commented
Feel free to merge when ready.

2020-10-27 03:14 UTC, ronaldtse requested changes

2020-10-27 03:14 UTC, ronaldtse commented on sources/guide-its-90/01-introduction.adoc
> +
Add `:si-aspect: K_k`

2020-10-28 00:17 UTC, manuel489 commented on sources/guide-its-90/01-introduction.adoc
> +
Done.
(I'm almost finished, one file remaining.)

2020-10-28 02:50 UTC, manuel489 commented on sources/guide-its-90/01-introduction.adoc
> +
All documents are converted.

2020-10-28 02:55 UTC, manuel489 commented
All documents from https://www.bipm.org/en/committees/cc/cct/guide-its90.html are converted

2020-10-28 03:05 UTC, ronaldtse approved these changes

2020-10-28 03:05 UTC, merged

2020-10-28 03:05 UTC, ronaldtse commented
Thank you @manuel489 !